about approval request
utofu/oauth-server pull request #1
Opened 2017-04-08 21:42 UTC by RikutoWatanabe

認可リクエスト処理と認可レスポンス処理を追加しました。
model内のClientクラスにfetch()、Grant_codeクラスにfetch_by_code()を作成しました。

2017-04-08 21:43 UTC, a-r-g-v commented on app/main/views.py
>  from flask import request
redirect を使用していますが，import されていないので import errorが発生します
```python
from flask import request, redirect
```
としてください

2017-04-08 21:46 UTC, a-r-g-v commented on app/main/views.py
> +        redirect_uri = request.args['redirect_uri']
request.args は Python の Dictionary ですが， Dictionary の Key Access は，そのキーが存在しない場合に KeyError という例外を発生させます．例外を処理する方法に書き直すか，`get` method を使用して キーが存在しない場合に返却するデフォルト値を明示する方法があります (http://www.lifewithpython.com/2015/05/python-dict-default-value.html )

```python
redirect_uri = request.get('redirect_uri', None)
if redirect_uri is None:
   # redirect_uri が空の時の処理
if redirect_uri is not None:
  # redirect_uri が空じゃない時の処理
```

2017-04-08 21:47 UTC, a-r-g-v commented on app/main/views.py
> +        client = Clients.fetch(client_id)
client_id が 空かどうか判定する前に，client_idを使用しています(できれば38行目で空じゃないと判定した移行にこの処理があるべきだと思います)

2017-04-08 21:58 UTC, a-r-g-v commented on app/main/views.py
> +            code = sha256(uuid4().hex).hexdigest()
ここで code を生成していますが， 保存されていないです．
`GrantCodes` クラスのインスタンスを作成して，`db.session.add` や `db.session.commit` を使用して， 生成した code を保存して下さい．

2017-04-08 22:09 UTC, a-r-g-v commented on app/main/views.py
> +@main.route('/approval', method=['GET','POST'])
method ではなく methods

2017-04-08 22:21 UTC, RikutoWatanabe commented on app/main/views.py
> +        redirect_uri = request.args['redirect_uri']
空白処理を宣言後すぐに追加しました。

2017-04-08 22:22 UTC, RikutoWatanabe commented on app/main/views.py
> +        client = Clients.fetch(client_id)
if文のclient_idが空白でないかを判断する処理をした後に再配置しました。

2017-04-08 22:22 UTC, RikutoWatanabe commented on app/main/views.py
> +            code = sha256(uuid4().hex).hexdigest()
データベースに追加する処理を追加しました

2017-04-08 22:23 UTC, RikutoWatanabe commented on app/main/views.py
> +@main.route('/approval', method=['GET','POST'])
すみません…。

2017-04-08 22:28 UTC, a-r-g-v commented on app/main/views.py
> +            client = Clients.fetch(client_id)
存在しない client_id が指定された時に，`Clients.fetch` は None を返却しますが，そのチェックがないようです

2017-04-08 22:29 UTC, a-r-g-v commented on app/main/views.py
> +            grant_code = GrantCodes.new(code,expire_date,user_id,client_id)
GrantCodes には new method が存在していません．自分で定義する必要があります．

2017-04-09 00:58 UTC, a-r-g-v commented on app/main/views.py
> +        if redirect_uri is None:
ここの処理が不要っぽいです

2017-04-09 00:59 UTC, a-r-g-v commented on app/main/views.py
> +        client = Clients.fetch(client_id)
Clients.fetch は Noneを返却する可能性があり，チェックがないです

2017-04-09 00:59 UTC, a-r-g-v commented on app/main/views.py
> +    client_id=request,form["client_id"]
, -> .

2017-04-09 00:59 UTC, a-r-g-v commented on app/main/views.py
> +    client = Clients.fetch(client_id)
None チェックが不足しています

2017-04-09 01:00 UTC, a-r-g-v commented on app/main/views.py
> +    if(Users.fetch(id,password) is None):
```
if not Users.fetch(id, password): 
```
の方が良さそうです

2017-04-09 01:01 UTC, a-r-g-v commented on app/main/views.py
> +    code = sha256(uuid4().hex).hexdigest()
この code, expire_date の処理は `GrantCodes.new`の中でやっても良さそうです

2017-04-09 01:01 UTC, a-r-g-v commented on app/main/views.py
> +    id=request.form["user_id"]
request.form.get() を使ったほうが良さそうです

2017-04-09 01:03 UTC, a-r-g-v commented on app/main/views.py
>  from ..models import Clients
```py
from ..models import Users, GrantCodes
```

2017-04-09 01:03 UTC, a-r-g-v commented on app/main/views.py
> +from flask import request, redirect
```py
from flask import request, redirect, render_template
````

2017-04-09 01:04 UTC, a-r-g-v commented on app/main/views.py
> +@app.route('/req_auth', methods=['POST'])
@app -> @main

2017-04-09 01:04 UTC, a-r-g-v commented on app/main/views.py
> +@app.route('/req_access',methods=['POST'])
@app -> @main

2017-04-09 01:04 UTC, a-r-g-v commented on app/main/views.py
> +    grant_code = GrantCodes.new(code,expire_date,scope,user_id,client_id,redirect_uri)
user_id ではなく id っぽいです

2017-04-09 02:24 UTC, a-r-g-v commented on app/models.py
> +        return cls(code=sha256(uuid4().hex).hexdigest(),expire_date=datetime.datetime.now()+datetime.timedelta(minutes=30),scope=scope,user_id=user_id,client_id=client_id,redirect_uri=redirect_uri)
```py
code = sha256(uuid4().hex).hexdigest()
expire_date = datetime.datetime.now()+datetime.timedelta(minutes=30)
return cls(code=code,expire_date=expire_date,scope=scope,user_id=user_id,client_id=client_id,redirect_uri=redirect_uri)
```

2017-04-09 02:27 UTC, a-r-g-v commented on app/main/views.py
> +    if redirect_uri is None:
68-71まで不要っぽいです

2017-04-09 02:27 UTC, a-r-g-v commented on app/main/views.py
> +    client = Clients.fetch(client_id)
client が None を返す可能性があります

2017-04-09 02:27 UTC, a-r-g-v commented on app/main/views.py
> +    grant_type = request.form["grant_type"]
request.form.get を使ったほうが良いです

2017-04-09 02:27 UTC, a-r-g-v commented on app/main/views.py
> +            redirect_uri == grant_code.redirect_uri
== になっていますが， = では？

2017-04-09 02:27 UTC, a-r-g-v commented on app/models.py
> +        'token_type': bearer,
bearer -> "bearer"

2017-04-09 02:27 UTC, a-r-g-v commented on app/models.py
> +        'expires_in': self.access_token_expire_date,
self.access_token_expire_date は datetime 型ですが，Responseに期待されるのは int 型の 期限切れまでの秒数です

2017-04-09 02:27 UTC, a-r-g-v commented on app/models.py
> +        'example_parameter': bearer
example_parameter は なくて大丈夫です

2017-04-09 03:14 UTC, a-r-g-v commented on app/main/views.py
> +@main.route('/approval', methods`=['GET','POST'])
methods` -> methods

2017-04-09 03:17 UTC, a-r-g-v commented on app/models.py
> +        return cls(access_token=sha256(uuid4().hex).hexdigest(),access_token_expire_date=datetime.datetime.now()+datetime.timedelta(hour=1),refresh_token=access_token=sha256(uuid4().hex).hexdigest(),
too long...

2017-04-09 03:18 UTC, a-r-g-v commented on app/models.py
> +        return cls(code=sha256(uuid4().hex).hexdigest(),expire_date=datetime.datetime.now()+datetime.timedelta(minutes=30),scope=scope,user_id=user_id,client_id=client_id,redirect_uri=redirect_uri)
too long...

2017-04-09 03:32 UTC, a-r-g-v commented on app/main/views.py
> +            if client is None:
indent

2017-04-09 03:32 UTC, a-r-g-v requested changes

2017-04-09 03:32 UTC, a-r-g-v commented on app/main/views.py
> +        if client is None:
indent

2017-04-09 03:33 UTC, a-r-g-v commented on app/main/views.py
> +    if #requestが不正 :
invalid syntax

2017-04-09 03:40 UTC, a-r-g-v commented on app/main/views.py
> +        #err msg
pass

2017-04-09 03:42 UTC, a-r-g-v commented on app/main/views.py
> +        return redirect(client.redirect_uri+"?error=invalid_request")
client がない

2017-04-09 03:42 UTC, a-r-g-v commented on app/main/views.py
> +        return redirect(client.redirect_uri+"?error=invalid_request")
clientがない

2017-04-09 03:42 UTC, a-r-g-v commented on app/main/views.py
> +            return redirect(client.redirect_uri+"?error=invalid_request")
clientがない

2017-04-09 03:43 UTC, a-r-g-v commented on app/main/views.py
> +            return redirect(client.redirect_uri+"?error=invalid_request")
clientがない

2017-04-09 03:43 UTC, a-r-g-v commented on app/main/views.py
> +                return redirect(client.redirect_uri+"?error=invalid_request")
clientがない

2017-04-09 03:44 UTC, a-r-g-v commented on app/main/views.py
> +    token = Tokens.new(access_token_expire_date,refresh_token_expire_date,_scopes,user_id,client_id,grant_code)
Tokensが import されていない
access_token_expire_date がない
refresh_token_expire_date がない
_scopes がない
user_id がない

2017-04-09 03:44 UTC, a-r-g-v commented on app/models.py
> +    r = {
indent error

2017-04-09 03:45 UTC, a-r-g-v commented on app/models.py
> +    if show_secret:
show_secret が未定義

2017-04-11 14:13 UTC, closed without merging